// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Torri.Data;

#nullable disable

namespace Torri.Migrations
{
    [DbContext(typeof(TorriContext))]
    partial class TorriContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Torri.Data.Entities.SerieMaskEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("FixSeason")
                        .HasColumnType("integer");

                    b.Property<string>("Mask")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TorrentEntityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TorrentEntityId");

                    b.ToTable("SerieMasks");
                });

            modelBuilder.Entity("Torri.Data.Entities.TorrentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("HasMissingRegex")
                        .HasColumnType("boolean");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("boolean");

                    b.Property<string>("TorrentName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("TorrentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.ToTable("Torrents");
                });

            modelBuilder.Entity("Torri.Data.Entities.VideoFileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EpisodeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("FileIndex")
                        .HasColumnType("integer");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<int>("TorrentEntityId")
                        .HasColumnType("integer");

                    b.Property<bool>("Wanted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("TorrentEntityId");

                    b.ToTable("VideoFiles");
                });

            modelBuilder.Entity("Torri.Data.Entities.SerieMaskEntity", b =>
                {
                    b.HasOne("Torri.Data.Entities.TorrentEntity", "TorrentEntity")
                        .WithMany("SerieMasks")
                        .HasForeignKey("TorrentEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TorrentEntity");
                });

            modelBuilder.Entity("Torri.Data.Entities.VideoFileEntity", b =>
                {
                    b.HasOne("Torri.Data.Entities.TorrentEntity", "TorrentEntity")
                        .WithMany("VideoFiles")
                        .HasForeignKey("TorrentEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TorrentEntity");
                });

            modelBuilder.Entity("Torri.Data.Entities.TorrentEntity", b =>
                {
                    b.Navigation("SerieMasks");

                    b.Navigation("VideoFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
